import { bigint, boolean, index, pgEnum, pgTable, real, text, timestamp } from "drizzle-orm/pg-core";
import { users } from "./users.js";
import { workspaces } from "./workspaces.js";

/**
 * The recording state machine: uploading -> ready | failed, and a
 * recoverable path back to `uploading` from `failed` so a retried upload
 * re-enters the same row rather than creating an orphan. Valid
 * transitions are enforced in code, not by the database, in
 * `../queries/recording-state.ts` — the enum only constrains the set of
 * values a row may hold.
 */
export const recordingStatusEnum = pgEnum("recording_status", ["uploading", "ready", "failed"]);

export const trimStatusEnum = pgEnum("trim_status", ["none", "pending", "processing", "ready", "failed"]);

/**
 * SPEC.md §12 "Link visibility": private (workspace members only),
 * unlisted (anyone with the link — the default), password (link + shared
 * password), expiring (any of the above plus a hard expiry).
 */
export const recordingVisibilityEnum = pgEnum("recording_visibility", [
  "private",
  "unlisted",
  "password",
  "expiring",
]);

/**
 * One row per recording. `publicId` is the value that appears in
 * `/v/<publicId>` — generated by `@recordmint/shared`'s `generatePublicId`
 * at insert time, never derived from `id`, so it carries no information
 * about creation order or row count.
 *
 * `objectKey` is the exact key written by `packages/storage`'s
 * `originalKey(recordingId, ext)` (STRUCTURE.md: the object layout is
 * defined in exactly one file) — this table stores that value, it does
 * not construct it.
 */
export const recordings = pgTable(
  "recordings",
  {
    id: text("id").primaryKey(),
    publicId: text("public_id").notNull().unique(),
    workspaceId: text("workspace_id")
      .notNull()
      .references(() => workspaces.id, { onDelete: "cascade" }),
    creatorId: text("creator_id")
      .notNull()
      .references(() => users.id, { onDelete: "restrict" }),

    title: text("title").notNull(),
    description: text("description"),

    status: recordingStatusEnum("status").notNull().default("uploading"),
    failureReason: text("failure_reason"),

    visibility: recordingVisibilityEnum("visibility").notNull().default("unlisted"),
    /** Argon2id hash of the share password. Only meaningful when visibility is "password". */
    passwordHash: text("password_hash"),
    /** Hard cutoff. Only meaningful when visibility is "expiring". */
    expiresAt: timestamp("expires_at", { withTimezone: true }),

    /**
     * SPEC.md §13: guest commenting on a shared link is per-recording and
     * off unless deliberately enabled, because a public link with open
     * commenting is a spam target and a self-hosted operator has no
     * moderation team. `false` is the most restrictive option, and this
     * column is the one place that default lives — nothing else in the
     * codebase may decide it independently.
     */
    guestCommentingEnabled: boolean("guest_commenting_enabled").notNull().default(false),

    /** The uploaded object's key under packages/storage's `recordings/<id>/` prefix. */
    objectKey: text("object_key").notNull(),
    /** "mp4" | "webm" — recorded so the player and any later remux know what they have. */
    container: text("container"),
    /** Raw codec string from MediaRecorder, e.g. "avc1.42E01E,mp4a.40.2". */
    codecs: text("codecs"),
    durationSeconds: real("duration_seconds"),
    sizeBytes: bigint("size_bytes", { mode: "number" }),

    /** The S3 multipart upload id. Non-null only while status = "uploading". */
    uploadId: text("upload_id"),
    /** packages/storage's `posterKey(recordingId)`, once the worker has produced one. */
    posterKey: text("poster_key"),
    trimStatus: trimStatusEnum("trim_status").notNull().default("none"),
    trimStartSeconds: real("trim_start_seconds"),
    trimEndSeconds: real("trim_end_seconds"),
    trimmedObjectKey: text("trimmed_object_key"),
    trimmedDurationSeconds: real("trimmed_duration_seconds"),
    trimFailureReason: text("trim_failure_reason"),

    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => ({
    workspaceIdx: index("recordings_workspace_id_idx").on(table.workspaceId),
    creatorIdx: index("recordings_creator_id_idx").on(table.creatorId),
    statusIdx: index("recordings_status_idx").on(table.status),
  }),
);
